SCREEN_WIDTH equ 320
SCREEN_HEIGHT equ 200
SCREEN_SIZE equ SCREEN_WIDTH*SCREEN_HEIGHT

BOARD_SIZE equ 180
BOARD_WIDTH equ BOARD_SIZE
BOARD_HEIGHT equ BOARD_SIZE

BOARD_POS_X equ 10
BOARD_POS_Y equ 10

BOARD_BORDER equ 2


SNAKE_WIDTH equ 2
SNAKE_INITIAL_SEGMENTS equ 4