; GAME GEOMETRY

SNAKE_WIDTH equ 4
SNAKE_INITIAL_SEGMENTS equ 4
BOARD_SIZE equ 180

; VISUAL:

BOARD_POS_X equ (SCREEN_WIDTH-BOARD_SIZE)/2
BOARD_POS_Y equ (SCREEN_HEIGHT-BOARD_SIZE)/2 ; centered

BOARD_BORDER equ 2

SCORE_POSITION_X equ (SCREEN_WIDTH+BOARD_SIZE)/2 + 16
SCORE_POSITION_Y equ (SCREEN_HEIGHT-BOARD_SIZE)/2 + 8

; COLORS (set to unique values):

CELL_EMPTY equ COLOR_BLACK
CELL_SNAKE equ COLOR_LIGHT_GREEN
CELL_SNAKE_FULL equ COLOR_YELLOW
CELL_FOOD equ COLOR_LIGHT_RED

COLOR_BORDER equ COLOR_WHITE
COLOR_BACKGROUND equ COLOR_ANOTHER_BLACK

; Hacks:

%define UNSAFE_BIOS_CALLS 1; -8 B
%define UNSAFE_CLOCK 1; -1 B
%define UNSAFE_IDK 1; -1 B

%define SIMPLIFIED_TAIL_STATE_MACHINE 1; -2 B

%define GLOBALS_IN_DEAD_CODE; -5 B

; Features:

;%define FEAT_HALT +1 B