; GAME GEOMETRY

SNAKE_WIDTH equ 4
SNAKE_INITIAL_SEGMENTS equ 4
BOARD_SIZE equ 180

; VISUAL:

BOARD_POS_X equ 10
BOARD_POS_Y equ 10

BOARD_BORDER equ 2

SCORE_POSITION_X equ 216
SCORE_POSITION_Y equ 16

%define UNSAFE_BIOS_CALLS 0
%define UNSAFE_CLOCK 0
%define UNSAFE_IDK 0